/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fastcomments.invoker.JSON;

/**
 * APITenantDailyUsage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class APITenantDailyUsage {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  @javax.annotation.Nonnull
  private String tenantId;

  public static final String SERIALIZED_NAME_YEAR_NUMBER = "yearNumber";
  @SerializedName(SERIALIZED_NAME_YEAR_NUMBER)
  @javax.annotation.Nonnull
  private Double yearNumber;

  public static final String SERIALIZED_NAME_MONTH_NUMBER = "monthNumber";
  @SerializedName(SERIALIZED_NAME_MONTH_NUMBER)
  @javax.annotation.Nonnull
  private Double monthNumber;

  public static final String SERIALIZED_NAME_DAY_NUMBER = "dayNumber";
  @SerializedName(SERIALIZED_NAME_DAY_NUMBER)
  @javax.annotation.Nonnull
  private Double dayNumber;

  public static final String SERIALIZED_NAME_COMMENT_FETCH_COUNT = "commentFetchCount";
  @SerializedName(SERIALIZED_NAME_COMMENT_FETCH_COUNT)
  @javax.annotation.Nonnull
  private Double commentFetchCount;

  public static final String SERIALIZED_NAME_COMMENT_CREATE_COUNT = "commentCreateCount";
  @SerializedName(SERIALIZED_NAME_COMMENT_CREATE_COUNT)
  @javax.annotation.Nonnull
  private Double commentCreateCount;

  public static final String SERIALIZED_NAME_CONVERSATION_CREATE_COUNT = "conversationCreateCount";
  @SerializedName(SERIALIZED_NAME_CONVERSATION_CREATE_COUNT)
  @javax.annotation.Nonnull
  private Double conversationCreateCount;

  public static final String SERIALIZED_NAME_VOTE_COUNT = "voteCount";
  @SerializedName(SERIALIZED_NAME_VOTE_COUNT)
  @javax.annotation.Nonnull
  private Double voteCount;

  public static final String SERIALIZED_NAME_ACCOUNT_CREATED_COUNT = "accountCreatedCount";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_CREATED_COUNT)
  @javax.annotation.Nonnull
  private Double accountCreatedCount;

  public static final String SERIALIZED_NAME_USER_MENTION_SEARCH = "userMentionSearch";
  @SerializedName(SERIALIZED_NAME_USER_MENTION_SEARCH)
  @javax.annotation.Nonnull
  private Double userMentionSearch;

  public static final String SERIALIZED_NAME_HASH_TAG_SEARCH = "hashTagSearch";
  @SerializedName(SERIALIZED_NAME_HASH_TAG_SEARCH)
  @javax.annotation.Nonnull
  private Double hashTagSearch;

  public static final String SERIALIZED_NAME_GIF_SEARCH_TRENDING = "gifSearchTrending";
  @SerializedName(SERIALIZED_NAME_GIF_SEARCH_TRENDING)
  @javax.annotation.Nonnull
  private Double gifSearchTrending;

  public static final String SERIALIZED_NAME_GIF_SEARCH = "gifSearch";
  @SerializedName(SERIALIZED_NAME_GIF_SEARCH)
  @javax.annotation.Nonnull
  private Double gifSearch;

  public static final String SERIALIZED_NAME_API_CREDITS_USED = "apiCreditsUsed";
  @SerializedName(SERIALIZED_NAME_API_CREDITS_USED)
  @javax.annotation.Nonnull
  private Double apiCreditsUsed;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_BILLED = "billed";
  @SerializedName(SERIALIZED_NAME_BILLED)
  @javax.annotation.Nonnull
  private Boolean billed;

  public static final String SERIALIZED_NAME_IGNORED = "ignored";
  @SerializedName(SERIALIZED_NAME_IGNORED)
  @javax.annotation.Nonnull
  private Boolean ignored;

  public static final String SERIALIZED_NAME_API_ERROR_COUNT = "apiErrorCount";
  @SerializedName(SERIALIZED_NAME_API_ERROR_COUNT)
  @javax.annotation.Nonnull
  private Double apiErrorCount;

  public APITenantDailyUsage() {
  }

  public APITenantDailyUsage id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public APITenantDailyUsage tenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nonnull
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
  }


  public APITenantDailyUsage yearNumber(@javax.annotation.Nonnull Double yearNumber) {
    this.yearNumber = yearNumber;
    return this;
  }

  /**
   * Get yearNumber
   * @return yearNumber
   */
  @javax.annotation.Nonnull
  public Double getYearNumber() {
    return yearNumber;
  }

  public void setYearNumber(@javax.annotation.Nonnull Double yearNumber) {
    this.yearNumber = yearNumber;
  }


  public APITenantDailyUsage monthNumber(@javax.annotation.Nonnull Double monthNumber) {
    this.monthNumber = monthNumber;
    return this;
  }

  /**
   * Get monthNumber
   * @return monthNumber
   */
  @javax.annotation.Nonnull
  public Double getMonthNumber() {
    return monthNumber;
  }

  public void setMonthNumber(@javax.annotation.Nonnull Double monthNumber) {
    this.monthNumber = monthNumber;
  }


  public APITenantDailyUsage dayNumber(@javax.annotation.Nonnull Double dayNumber) {
    this.dayNumber = dayNumber;
    return this;
  }

  /**
   * Get dayNumber
   * @return dayNumber
   */
  @javax.annotation.Nonnull
  public Double getDayNumber() {
    return dayNumber;
  }

  public void setDayNumber(@javax.annotation.Nonnull Double dayNumber) {
    this.dayNumber = dayNumber;
  }


  public APITenantDailyUsage commentFetchCount(@javax.annotation.Nonnull Double commentFetchCount) {
    this.commentFetchCount = commentFetchCount;
    return this;
  }

  /**
   * Get commentFetchCount
   * @return commentFetchCount
   */
  @javax.annotation.Nonnull
  public Double getCommentFetchCount() {
    return commentFetchCount;
  }

  public void setCommentFetchCount(@javax.annotation.Nonnull Double commentFetchCount) {
    this.commentFetchCount = commentFetchCount;
  }


  public APITenantDailyUsage commentCreateCount(@javax.annotation.Nonnull Double commentCreateCount) {
    this.commentCreateCount = commentCreateCount;
    return this;
  }

  /**
   * Get commentCreateCount
   * @return commentCreateCount
   */
  @javax.annotation.Nonnull
  public Double getCommentCreateCount() {
    return commentCreateCount;
  }

  public void setCommentCreateCount(@javax.annotation.Nonnull Double commentCreateCount) {
    this.commentCreateCount = commentCreateCount;
  }


  public APITenantDailyUsage conversationCreateCount(@javax.annotation.Nonnull Double conversationCreateCount) {
    this.conversationCreateCount = conversationCreateCount;
    return this;
  }

  /**
   * Get conversationCreateCount
   * @return conversationCreateCount
   */
  @javax.annotation.Nonnull
  public Double getConversationCreateCount() {
    return conversationCreateCount;
  }

  public void setConversationCreateCount(@javax.annotation.Nonnull Double conversationCreateCount) {
    this.conversationCreateCount = conversationCreateCount;
  }


  public APITenantDailyUsage voteCount(@javax.annotation.Nonnull Double voteCount) {
    this.voteCount = voteCount;
    return this;
  }

  /**
   * Get voteCount
   * @return voteCount
   */
  @javax.annotation.Nonnull
  public Double getVoteCount() {
    return voteCount;
  }

  public void setVoteCount(@javax.annotation.Nonnull Double voteCount) {
    this.voteCount = voteCount;
  }


  public APITenantDailyUsage accountCreatedCount(@javax.annotation.Nonnull Double accountCreatedCount) {
    this.accountCreatedCount = accountCreatedCount;
    return this;
  }

  /**
   * Get accountCreatedCount
   * @return accountCreatedCount
   */
  @javax.annotation.Nonnull
  public Double getAccountCreatedCount() {
    return accountCreatedCount;
  }

  public void setAccountCreatedCount(@javax.annotation.Nonnull Double accountCreatedCount) {
    this.accountCreatedCount = accountCreatedCount;
  }


  public APITenantDailyUsage userMentionSearch(@javax.annotation.Nonnull Double userMentionSearch) {
    this.userMentionSearch = userMentionSearch;
    return this;
  }

  /**
   * Get userMentionSearch
   * @return userMentionSearch
   */
  @javax.annotation.Nonnull
  public Double getUserMentionSearch() {
    return userMentionSearch;
  }

  public void setUserMentionSearch(@javax.annotation.Nonnull Double userMentionSearch) {
    this.userMentionSearch = userMentionSearch;
  }


  public APITenantDailyUsage hashTagSearch(@javax.annotation.Nonnull Double hashTagSearch) {
    this.hashTagSearch = hashTagSearch;
    return this;
  }

  /**
   * Get hashTagSearch
   * @return hashTagSearch
   */
  @javax.annotation.Nonnull
  public Double getHashTagSearch() {
    return hashTagSearch;
  }

  public void setHashTagSearch(@javax.annotation.Nonnull Double hashTagSearch) {
    this.hashTagSearch = hashTagSearch;
  }


  public APITenantDailyUsage gifSearchTrending(@javax.annotation.Nonnull Double gifSearchTrending) {
    this.gifSearchTrending = gifSearchTrending;
    return this;
  }

  /**
   * Get gifSearchTrending
   * @return gifSearchTrending
   */
  @javax.annotation.Nonnull
  public Double getGifSearchTrending() {
    return gifSearchTrending;
  }

  public void setGifSearchTrending(@javax.annotation.Nonnull Double gifSearchTrending) {
    this.gifSearchTrending = gifSearchTrending;
  }


  public APITenantDailyUsage gifSearch(@javax.annotation.Nonnull Double gifSearch) {
    this.gifSearch = gifSearch;
    return this;
  }

  /**
   * Get gifSearch
   * @return gifSearch
   */
  @javax.annotation.Nonnull
  public Double getGifSearch() {
    return gifSearch;
  }

  public void setGifSearch(@javax.annotation.Nonnull Double gifSearch) {
    this.gifSearch = gifSearch;
  }


  public APITenantDailyUsage apiCreditsUsed(@javax.annotation.Nonnull Double apiCreditsUsed) {
    this.apiCreditsUsed = apiCreditsUsed;
    return this;
  }

  /**
   * Get apiCreditsUsed
   * @return apiCreditsUsed
   */
  @javax.annotation.Nonnull
  public Double getApiCreditsUsed() {
    return apiCreditsUsed;
  }

  public void setApiCreditsUsed(@javax.annotation.Nonnull Double apiCreditsUsed) {
    this.apiCreditsUsed = apiCreditsUsed;
  }


  public APITenantDailyUsage createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public APITenantDailyUsage billed(@javax.annotation.Nonnull Boolean billed) {
    this.billed = billed;
    return this;
  }

  /**
   * Get billed
   * @return billed
   */
  @javax.annotation.Nonnull
  public Boolean getBilled() {
    return billed;
  }

  public void setBilled(@javax.annotation.Nonnull Boolean billed) {
    this.billed = billed;
  }


  public APITenantDailyUsage ignored(@javax.annotation.Nonnull Boolean ignored) {
    this.ignored = ignored;
    return this;
  }

  /**
   * Get ignored
   * @return ignored
   */
  @javax.annotation.Nonnull
  public Boolean getIgnored() {
    return ignored;
  }

  public void setIgnored(@javax.annotation.Nonnull Boolean ignored) {
    this.ignored = ignored;
  }


  public APITenantDailyUsage apiErrorCount(@javax.annotation.Nonnull Double apiErrorCount) {
    this.apiErrorCount = apiErrorCount;
    return this;
  }

  /**
   * Get apiErrorCount
   * @return apiErrorCount
   */
  @javax.annotation.Nonnull
  public Double getApiErrorCount() {
    return apiErrorCount;
  }

  public void setApiErrorCount(@javax.annotation.Nonnull Double apiErrorCount) {
    this.apiErrorCount = apiErrorCount;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    APITenantDailyUsage apITenantDailyUsage = (APITenantDailyUsage) o;
    return Objects.equals(this.id, apITenantDailyUsage.id) &&
        Objects.equals(this.tenantId, apITenantDailyUsage.tenantId) &&
        Objects.equals(this.yearNumber, apITenantDailyUsage.yearNumber) &&
        Objects.equals(this.monthNumber, apITenantDailyUsage.monthNumber) &&
        Objects.equals(this.dayNumber, apITenantDailyUsage.dayNumber) &&
        Objects.equals(this.commentFetchCount, apITenantDailyUsage.commentFetchCount) &&
        Objects.equals(this.commentCreateCount, apITenantDailyUsage.commentCreateCount) &&
        Objects.equals(this.conversationCreateCount, apITenantDailyUsage.conversationCreateCount) &&
        Objects.equals(this.voteCount, apITenantDailyUsage.voteCount) &&
        Objects.equals(this.accountCreatedCount, apITenantDailyUsage.accountCreatedCount) &&
        Objects.equals(this.userMentionSearch, apITenantDailyUsage.userMentionSearch) &&
        Objects.equals(this.hashTagSearch, apITenantDailyUsage.hashTagSearch) &&
        Objects.equals(this.gifSearchTrending, apITenantDailyUsage.gifSearchTrending) &&
        Objects.equals(this.gifSearch, apITenantDailyUsage.gifSearch) &&
        Objects.equals(this.apiCreditsUsed, apITenantDailyUsage.apiCreditsUsed) &&
        Objects.equals(this.createdAt, apITenantDailyUsage.createdAt) &&
        Objects.equals(this.billed, apITenantDailyUsage.billed) &&
        Objects.equals(this.ignored, apITenantDailyUsage.ignored) &&
        Objects.equals(this.apiErrorCount, apITenantDailyUsage.apiErrorCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, yearNumber, monthNumber, dayNumber, commentFetchCount, commentCreateCount, conversationCreateCount, voteCount, accountCreatedCount, userMentionSearch, hashTagSearch, gifSearchTrending, gifSearch, apiCreditsUsed, createdAt, billed, ignored, apiErrorCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APITenantDailyUsage {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    yearNumber: ").append(toIndentedString(yearNumber)).append("\n");
    sb.append("    monthNumber: ").append(toIndentedString(monthNumber)).append("\n");
    sb.append("    dayNumber: ").append(toIndentedString(dayNumber)).append("\n");
    sb.append("    commentFetchCount: ").append(toIndentedString(commentFetchCount)).append("\n");
    sb.append("    commentCreateCount: ").append(toIndentedString(commentCreateCount)).append("\n");
    sb.append("    conversationCreateCount: ").append(toIndentedString(conversationCreateCount)).append("\n");
    sb.append("    voteCount: ").append(toIndentedString(voteCount)).append("\n");
    sb.append("    accountCreatedCount: ").append(toIndentedString(accountCreatedCount)).append("\n");
    sb.append("    userMentionSearch: ").append(toIndentedString(userMentionSearch)).append("\n");
    sb.append("    hashTagSearch: ").append(toIndentedString(hashTagSearch)).append("\n");
    sb.append("    gifSearchTrending: ").append(toIndentedString(gifSearchTrending)).append("\n");
    sb.append("    gifSearch: ").append(toIndentedString(gifSearch)).append("\n");
    sb.append("    apiCreditsUsed: ").append(toIndentedString(apiCreditsUsed)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    billed: ").append(toIndentedString(billed)).append("\n");
    sb.append("    ignored: ").append(toIndentedString(ignored)).append("\n");
    sb.append("    apiErrorCount: ").append(toIndentedString(apiErrorCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("tenantId");
    openapiFields.add("yearNumber");
    openapiFields.add("monthNumber");
    openapiFields.add("dayNumber");
    openapiFields.add("commentFetchCount");
    openapiFields.add("commentCreateCount");
    openapiFields.add("conversationCreateCount");
    openapiFields.add("voteCount");
    openapiFields.add("accountCreatedCount");
    openapiFields.add("userMentionSearch");
    openapiFields.add("hashTagSearch");
    openapiFields.add("gifSearchTrending");
    openapiFields.add("gifSearch");
    openapiFields.add("apiCreditsUsed");
    openapiFields.add("createdAt");
    openapiFields.add("billed");
    openapiFields.add("ignored");
    openapiFields.add("apiErrorCount");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("tenantId");
    openapiRequiredFields.add("yearNumber");
    openapiRequiredFields.add("monthNumber");
    openapiRequiredFields.add("dayNumber");
    openapiRequiredFields.add("commentFetchCount");
    openapiRequiredFields.add("commentCreateCount");
    openapiRequiredFields.add("conversationCreateCount");
    openapiRequiredFields.add("voteCount");
    openapiRequiredFields.add("accountCreatedCount");
    openapiRequiredFields.add("userMentionSearch");
    openapiRequiredFields.add("hashTagSearch");
    openapiRequiredFields.add("gifSearchTrending");
    openapiRequiredFields.add("gifSearch");
    openapiRequiredFields.add("apiCreditsUsed");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("billed");
    openapiRequiredFields.add("ignored");
    openapiRequiredFields.add("apiErrorCount");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to APITenantDailyUsage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!APITenantDailyUsage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in APITenantDailyUsage is not found in the empty JSON string", APITenantDailyUsage.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!APITenantDailyUsage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `APITenantDailyUsage` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : APITenantDailyUsage.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!APITenantDailyUsage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'APITenantDailyUsage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<APITenantDailyUsage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(APITenantDailyUsage.class));

       return (TypeAdapter<T>) new TypeAdapter<APITenantDailyUsage>() {
           @Override
           public void write(JsonWriter out, APITenantDailyUsage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public APITenantDailyUsage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of APITenantDailyUsage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of APITenantDailyUsage
   * @throws IOException if the JSON string is invalid with respect to APITenantDailyUsage
   */
  public static APITenantDailyUsage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, APITenantDailyUsage.class);
  }

  /**
   * Convert an instance of APITenantDailyUsage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

