/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets CommentQuestionsRequired
 */
@JsonAdapter(CommentQuestionsRequired.Adapter.class)
public enum CommentQuestionsRequired {
  
  NUMBER_0(0),
  
  NUMBER_1(1);

  private Integer value;

  CommentQuestionsRequired(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CommentQuestionsRequired fromValue(Integer value) {
    for (CommentQuestionsRequired b : CommentQuestionsRequired.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<CommentQuestionsRequired> {
    @Override
    public void write(final JsonWriter jsonWriter, final CommentQuestionsRequired enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CommentQuestionsRequired read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return CommentQuestionsRequired.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    Integer value = jsonElement.getAsInt();
    CommentQuestionsRequired.fromValue(value);
  }
}

