/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.fastcomments.model.APIStatus;
import com.fastcomments.model.PendingCommentToSyncOutbound;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fastcomments.invoker.JSON;

/**
 * GetPendingWebhookEventsResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GetPendingWebhookEventsResponse {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private APIStatus status;

  public static final String SERIALIZED_NAME_PENDING_WEBHOOK_EVENTS = "pendingWebhookEvents";
  @SerializedName(SERIALIZED_NAME_PENDING_WEBHOOK_EVENTS)
  @javax.annotation.Nonnull
  private List<PendingCommentToSyncOutbound> pendingWebhookEvents = new ArrayList<>();

  public GetPendingWebhookEventsResponse() {
  }

  public GetPendingWebhookEventsResponse status(@javax.annotation.Nonnull APIStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public APIStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull APIStatus status) {
    this.status = status;
  }


  public GetPendingWebhookEventsResponse pendingWebhookEvents(@javax.annotation.Nonnull List<PendingCommentToSyncOutbound> pendingWebhookEvents) {
    this.pendingWebhookEvents = pendingWebhookEvents;
    return this;
  }

  public GetPendingWebhookEventsResponse addPendingWebhookEventsItem(PendingCommentToSyncOutbound pendingWebhookEventsItem) {
    if (this.pendingWebhookEvents == null) {
      this.pendingWebhookEvents = new ArrayList<>();
    }
    this.pendingWebhookEvents.add(pendingWebhookEventsItem);
    return this;
  }

  /**
   * Get pendingWebhookEvents
   * @return pendingWebhookEvents
   */
  @javax.annotation.Nonnull
  public List<PendingCommentToSyncOutbound> getPendingWebhookEvents() {
    return pendingWebhookEvents;
  }

  public void setPendingWebhookEvents(@javax.annotation.Nonnull List<PendingCommentToSyncOutbound> pendingWebhookEvents) {
    this.pendingWebhookEvents = pendingWebhookEvents;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPendingWebhookEventsResponse getPendingWebhookEventsResponse = (GetPendingWebhookEventsResponse) o;
    return Objects.equals(this.status, getPendingWebhookEventsResponse.status) &&
        Objects.equals(this.pendingWebhookEvents, getPendingWebhookEventsResponse.pendingWebhookEvents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, pendingWebhookEvents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPendingWebhookEventsResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    pendingWebhookEvents: ").append(toIndentedString(pendingWebhookEvents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("pendingWebhookEvents");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("pendingWebhookEvents");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetPendingWebhookEventsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetPendingWebhookEventsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetPendingWebhookEventsResponse is not found in the empty JSON string", GetPendingWebhookEventsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetPendingWebhookEventsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetPendingWebhookEventsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetPendingWebhookEventsResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `status`
      APIStatus.validateJsonElement(jsonObj.get("status"));
      // ensure the json data is an array
      if (!jsonObj.get("pendingWebhookEvents").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `pendingWebhookEvents` to be an array in the JSON string but got `%s`", jsonObj.get("pendingWebhookEvents").toString()));
      }

      JsonArray jsonArraypendingWebhookEvents = jsonObj.getAsJsonArray("pendingWebhookEvents");
      // validate the required field `pendingWebhookEvents` (array)
      for (int i = 0; i < jsonArraypendingWebhookEvents.size(); i++) {
        PendingCommentToSyncOutbound.validateJsonElement(jsonArraypendingWebhookEvents.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetPendingWebhookEventsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetPendingWebhookEventsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetPendingWebhookEventsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetPendingWebhookEventsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetPendingWebhookEventsResponse>() {
           @Override
           public void write(JsonWriter out, GetPendingWebhookEventsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetPendingWebhookEventsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetPendingWebhookEventsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetPendingWebhookEventsResponse
   * @throws IOException if the JSON string is invalid with respect to GetPendingWebhookEventsResponse
   */
  public static GetPendingWebhookEventsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetPendingWebhookEventsResponse.class);
  }

  /**
   * Convert an instance of GetPendingWebhookEventsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

