/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.fastcomments.model.APIStatus;
import com.fastcomments.model.APITenantDailyUsage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fastcomments.invoker.JSON;

/**
 * GetTenantDailyUsagesResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GetTenantDailyUsagesResponse {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private APIStatus status;

  public static final String SERIALIZED_NAME_TENANT_DAILY_USAGES = "tenantDailyUsages";
  @SerializedName(SERIALIZED_NAME_TENANT_DAILY_USAGES)
  @javax.annotation.Nonnull
  private List<APITenantDailyUsage> tenantDailyUsages = new ArrayList<>();

  public GetTenantDailyUsagesResponse() {
  }

  public GetTenantDailyUsagesResponse status(@javax.annotation.Nonnull APIStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public APIStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull APIStatus status) {
    this.status = status;
  }


  public GetTenantDailyUsagesResponse tenantDailyUsages(@javax.annotation.Nonnull List<APITenantDailyUsage> tenantDailyUsages) {
    this.tenantDailyUsages = tenantDailyUsages;
    return this;
  }

  public GetTenantDailyUsagesResponse addTenantDailyUsagesItem(APITenantDailyUsage tenantDailyUsagesItem) {
    if (this.tenantDailyUsages == null) {
      this.tenantDailyUsages = new ArrayList<>();
    }
    this.tenantDailyUsages.add(tenantDailyUsagesItem);
    return this;
  }

  /**
   * Get tenantDailyUsages
   * @return tenantDailyUsages
   */
  @javax.annotation.Nonnull
  public List<APITenantDailyUsage> getTenantDailyUsages() {
    return tenantDailyUsages;
  }

  public void setTenantDailyUsages(@javax.annotation.Nonnull List<APITenantDailyUsage> tenantDailyUsages) {
    this.tenantDailyUsages = tenantDailyUsages;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTenantDailyUsagesResponse getTenantDailyUsagesResponse = (GetTenantDailyUsagesResponse) o;
    return Objects.equals(this.status, getTenantDailyUsagesResponse.status) &&
        Objects.equals(this.tenantDailyUsages, getTenantDailyUsagesResponse.tenantDailyUsages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, tenantDailyUsages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTenantDailyUsagesResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tenantDailyUsages: ").append(toIndentedString(tenantDailyUsages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("tenantDailyUsages");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("tenantDailyUsages");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetTenantDailyUsagesResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetTenantDailyUsagesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetTenantDailyUsagesResponse is not found in the empty JSON string", GetTenantDailyUsagesResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetTenantDailyUsagesResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetTenantDailyUsagesResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetTenantDailyUsagesResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `status`
      APIStatus.validateJsonElement(jsonObj.get("status"));
      // ensure the json data is an array
      if (!jsonObj.get("tenantDailyUsages").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantDailyUsages` to be an array in the JSON string but got `%s`", jsonObj.get("tenantDailyUsages").toString()));
      }

      JsonArray jsonArraytenantDailyUsages = jsonObj.getAsJsonArray("tenantDailyUsages");
      // validate the required field `tenantDailyUsages` (array)
      for (int i = 0; i < jsonArraytenantDailyUsages.size(); i++) {
        APITenantDailyUsage.validateJsonElement(jsonArraytenantDailyUsages.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetTenantDailyUsagesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetTenantDailyUsagesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetTenantDailyUsagesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetTenantDailyUsagesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetTenantDailyUsagesResponse>() {
           @Override
           public void write(JsonWriter out, GetTenantDailyUsagesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetTenantDailyUsagesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetTenantDailyUsagesResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetTenantDailyUsagesResponse
   * @throws IOException if the JSON string is invalid with respect to GetTenantDailyUsagesResponse
   */
  public static GetTenantDailyUsagesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetTenantDailyUsagesResponse.class);
  }

  /**
   * Convert an instance of GetTenantDailyUsagesResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

