/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.fastcomments.model.APIStatus;
import com.fastcomments.model.APITicketDetail;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fastcomments.invoker.JSON;

/**
 * GetTicketResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0-SNAPSHOT")
public class GetTicketResponse {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private APIStatus status;

  public static final String SERIALIZED_NAME_TICKET = "ticket";
  @SerializedName(SERIALIZED_NAME_TICKET)
  @javax.annotation.Nonnull
  private APITicketDetail ticket;

  public static final String SERIALIZED_NAME_AVAILABLE_STATES = "availableStates";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_STATES)
  @javax.annotation.Nonnull
  private List<Double> availableStates = new ArrayList<>();

  public GetTicketResponse() {
  }

  public GetTicketResponse status(@javax.annotation.Nonnull APIStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public APIStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull APIStatus status) {
    this.status = status;
  }


  public GetTicketResponse ticket(@javax.annotation.Nonnull APITicketDetail ticket) {
    this.ticket = ticket;
    return this;
  }

  /**
   * Get ticket
   * @return ticket
   */
  @javax.annotation.Nonnull
  public APITicketDetail getTicket() {
    return ticket;
  }

  public void setTicket(@javax.annotation.Nonnull APITicketDetail ticket) {
    this.ticket = ticket;
  }


  public GetTicketResponse availableStates(@javax.annotation.Nonnull List<Double> availableStates) {
    this.availableStates = availableStates;
    return this;
  }

  public GetTicketResponse addAvailableStatesItem(Double availableStatesItem) {
    if (this.availableStates == null) {
      this.availableStates = new ArrayList<>();
    }
    this.availableStates.add(availableStatesItem);
    return this;
  }

  /**
   * Get availableStates
   * @return availableStates
   */
  @javax.annotation.Nonnull
  public List<Double> getAvailableStates() {
    return availableStates;
  }

  public void setAvailableStates(@javax.annotation.Nonnull List<Double> availableStates) {
    this.availableStates = availableStates;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTicketResponse getTicketResponse = (GetTicketResponse) o;
    return Objects.equals(this.status, getTicketResponse.status) &&
        Objects.equals(this.ticket, getTicketResponse.ticket) &&
        Objects.equals(this.availableStates, getTicketResponse.availableStates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, ticket, availableStates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTicketResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    ticket: ").append(toIndentedString(ticket)).append("\n");
    sb.append("    availableStates: ").append(toIndentedString(availableStates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("status", "ticket", "availableStates"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("status", "ticket", "availableStates"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetTicketResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetTicketResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in GetTicketResponse is not found in the empty JSON string", GetTicketResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetTicketResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `GetTicketResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetTicketResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `status`
      APIStatus.validateJsonElement(jsonObj.get("status"));
      // validate the required field `ticket`
      APITicketDetail.validateJsonElement(jsonObj.get("ticket"));
      // ensure the required json array is present
      if (jsonObj.get("availableStates") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("availableStates").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `availableStates` to be an array in the JSON string but got `%s`", jsonObj.get("availableStates").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetTicketResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetTicketResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetTicketResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetTicketResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetTicketResponse>() {
           @Override
           public void write(JsonWriter out, GetTicketResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetTicketResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetTicketResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetTicketResponse
   * @throws IOException if the JSON string is invalid with respect to GetTicketResponse
   */
  public static GetTicketResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetTicketResponse.class);
  }

  /**
   * Convert an instance of GetTicketResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

