/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.fastcomments.model.APIStatus;
import com.fastcomments.model.TenantPackage;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fastcomments.invoker.JSON;

/**
 * GetTenantPackagesResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class GetTenantPackagesResponse {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private APIStatus status;

  public static final String SERIALIZED_NAME_TENANT_PACKAGES = "tenantPackages";
  @SerializedName(SERIALIZED_NAME_TENANT_PACKAGES)
  @javax.annotation.Nonnull
  private List<TenantPackage> tenantPackages = new ArrayList<>();

  public GetTenantPackagesResponse() {
  }

  public GetTenantPackagesResponse status(@javax.annotation.Nonnull APIStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public APIStatus getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull APIStatus status) {
    this.status = status;
  }


  public GetTenantPackagesResponse tenantPackages(@javax.annotation.Nonnull List<TenantPackage> tenantPackages) {
    this.tenantPackages = tenantPackages;
    return this;
  }

  public GetTenantPackagesResponse addTenantPackagesItem(TenantPackage tenantPackagesItem) {
    if (this.tenantPackages == null) {
      this.tenantPackages = new ArrayList<>();
    }
    this.tenantPackages.add(tenantPackagesItem);
    return this;
  }

  /**
   * Get tenantPackages
   * @return tenantPackages
   */
  @javax.annotation.Nonnull
  public List<TenantPackage> getTenantPackages() {
    return tenantPackages;
  }

  public void setTenantPackages(@javax.annotation.Nonnull List<TenantPackage> tenantPackages) {
    this.tenantPackages = tenantPackages;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTenantPackagesResponse getTenantPackagesResponse = (GetTenantPackagesResponse) o;
    return Objects.equals(this.status, getTenantPackagesResponse.status) &&
        Objects.equals(this.tenantPackages, getTenantPackagesResponse.tenantPackages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, tenantPackages);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTenantPackagesResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    tenantPackages: ").append(toIndentedString(tenantPackages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("tenantPackages");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("tenantPackages");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetTenantPackagesResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetTenantPackagesResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetTenantPackagesResponse is not found in the empty JSON string", GetTenantPackagesResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetTenantPackagesResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetTenantPackagesResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetTenantPackagesResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `status`
      APIStatus.validateJsonElement(jsonObj.get("status"));
      // ensure the json data is an array
      if (!jsonObj.get("tenantPackages").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantPackages` to be an array in the JSON string but got `%s`", jsonObj.get("tenantPackages").toString()));
      }

      JsonArray jsonArraytenantPackages = jsonObj.getAsJsonArray("tenantPackages");
      // validate the required field `tenantPackages` (array)
      for (int i = 0; i < jsonArraytenantPackages.size(); i++) {
        TenantPackage.validateJsonElement(jsonArraytenantPackages.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetTenantPackagesResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetTenantPackagesResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetTenantPackagesResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetTenantPackagesResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetTenantPackagesResponse>() {
           @Override
           public void write(JsonWriter out, GetTenantPackagesResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetTenantPackagesResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetTenantPackagesResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetTenantPackagesResponse
   * @throws IOException if the JSON string is invalid with respect to GetTenantPackagesResponse
   */
  public static GetTenantPackagesResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetTenantPackagesResponse.class);
  }

  /**
   * Convert an instance of GetTenantPackagesResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

