/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fastcomments.invoker.JSON;

/**
 * Moderator
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class Moderator {
  public static final String SERIALIZED_NAME_ID = "_id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenantId";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  @javax.annotation.Nonnull
  private String tenantId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  public static final String SERIALIZED_NAME_ACCEPTED_INVITE = "acceptedInvite";
  @SerializedName(SERIALIZED_NAME_ACCEPTED_INVITE)
  @javax.annotation.Nonnull
  private Boolean acceptedInvite;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_MARK_REVIEWED_COUNT = "markReviewedCount";
  @SerializedName(SERIALIZED_NAME_MARK_REVIEWED_COUNT)
  @javax.annotation.Nonnull
  private Double markReviewedCount;

  public static final String SERIALIZED_NAME_DELETED_COUNT = "deletedCount";
  @SerializedName(SERIALIZED_NAME_DELETED_COUNT)
  @javax.annotation.Nonnull
  private Double deletedCount;

  public static final String SERIALIZED_NAME_MARKED_SPAM_COUNT = "markedSpamCount";
  @SerializedName(SERIALIZED_NAME_MARKED_SPAM_COUNT)
  @javax.annotation.Nonnull
  private Double markedSpamCount;

  public static final String SERIALIZED_NAME_MARKED_NOT_SPAM_COUNT = "markedNotSpamCount";
  @SerializedName(SERIALIZED_NAME_MARKED_NOT_SPAM_COUNT)
  @javax.annotation.Nonnull
  private Double markedNotSpamCount;

  public static final String SERIALIZED_NAME_APPROVED_COUNT = "approvedCount";
  @SerializedName(SERIALIZED_NAME_APPROVED_COUNT)
  @javax.annotation.Nonnull
  private Double approvedCount;

  public static final String SERIALIZED_NAME_UN_APPROVED_COUNT = "unApprovedCount";
  @SerializedName(SERIALIZED_NAME_UN_APPROVED_COUNT)
  @javax.annotation.Nonnull
  private Double unApprovedCount;

  public static final String SERIALIZED_NAME_EDITED_COUNT = "editedCount";
  @SerializedName(SERIALIZED_NAME_EDITED_COUNT)
  @javax.annotation.Nonnull
  private Double editedCount;

  public static final String SERIALIZED_NAME_BANNED_COUNT = "bannedCount";
  @SerializedName(SERIALIZED_NAME_BANNED_COUNT)
  @javax.annotation.Nonnull
  private Double bannedCount;

  public static final String SERIALIZED_NAME_UN_FLAGGED_COUNT = "unFlaggedCount";
  @SerializedName(SERIALIZED_NAME_UN_FLAGGED_COUNT)
  @javax.annotation.Nonnull
  private Double unFlaggedCount;

  public static final String SERIALIZED_NAME_VERIFICATION_ID = "verificationId";
  @SerializedName(SERIALIZED_NAME_VERIFICATION_ID)
  @javax.annotation.Nullable
  private String verificationId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_MODERATION_GROUP_IDS = "moderationGroupIds";
  @SerializedName(SERIALIZED_NAME_MODERATION_GROUP_IDS)
  @javax.annotation.Nullable
  private List<String> moderationGroupIds;

  public Moderator() {
  }

  public Moderator id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public Moderator tenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nonnull
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
  }


  public Moderator name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Moderator userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public Moderator acceptedInvite(@javax.annotation.Nonnull Boolean acceptedInvite) {
    this.acceptedInvite = acceptedInvite;
    return this;
  }

  /**
   * Get acceptedInvite
   * @return acceptedInvite
   */
  @javax.annotation.Nonnull
  public Boolean getAcceptedInvite() {
    return acceptedInvite;
  }

  public void setAcceptedInvite(@javax.annotation.Nonnull Boolean acceptedInvite) {
    this.acceptedInvite = acceptedInvite;
  }


  public Moderator email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public Moderator markReviewedCount(@javax.annotation.Nonnull Double markReviewedCount) {
    this.markReviewedCount = markReviewedCount;
    return this;
  }

  /**
   * Get markReviewedCount
   * @return markReviewedCount
   */
  @javax.annotation.Nonnull
  public Double getMarkReviewedCount() {
    return markReviewedCount;
  }

  public void setMarkReviewedCount(@javax.annotation.Nonnull Double markReviewedCount) {
    this.markReviewedCount = markReviewedCount;
  }


  public Moderator deletedCount(@javax.annotation.Nonnull Double deletedCount) {
    this.deletedCount = deletedCount;
    return this;
  }

  /**
   * Get deletedCount
   * @return deletedCount
   */
  @javax.annotation.Nonnull
  public Double getDeletedCount() {
    return deletedCount;
  }

  public void setDeletedCount(@javax.annotation.Nonnull Double deletedCount) {
    this.deletedCount = deletedCount;
  }


  public Moderator markedSpamCount(@javax.annotation.Nonnull Double markedSpamCount) {
    this.markedSpamCount = markedSpamCount;
    return this;
  }

  /**
   * Get markedSpamCount
   * @return markedSpamCount
   */
  @javax.annotation.Nonnull
  public Double getMarkedSpamCount() {
    return markedSpamCount;
  }

  public void setMarkedSpamCount(@javax.annotation.Nonnull Double markedSpamCount) {
    this.markedSpamCount = markedSpamCount;
  }


  public Moderator markedNotSpamCount(@javax.annotation.Nonnull Double markedNotSpamCount) {
    this.markedNotSpamCount = markedNotSpamCount;
    return this;
  }

  /**
   * Get markedNotSpamCount
   * @return markedNotSpamCount
   */
  @javax.annotation.Nonnull
  public Double getMarkedNotSpamCount() {
    return markedNotSpamCount;
  }

  public void setMarkedNotSpamCount(@javax.annotation.Nonnull Double markedNotSpamCount) {
    this.markedNotSpamCount = markedNotSpamCount;
  }


  public Moderator approvedCount(@javax.annotation.Nonnull Double approvedCount) {
    this.approvedCount = approvedCount;
    return this;
  }

  /**
   * Get approvedCount
   * @return approvedCount
   */
  @javax.annotation.Nonnull
  public Double getApprovedCount() {
    return approvedCount;
  }

  public void setApprovedCount(@javax.annotation.Nonnull Double approvedCount) {
    this.approvedCount = approvedCount;
  }


  public Moderator unApprovedCount(@javax.annotation.Nonnull Double unApprovedCount) {
    this.unApprovedCount = unApprovedCount;
    return this;
  }

  /**
   * Get unApprovedCount
   * @return unApprovedCount
   */
  @javax.annotation.Nonnull
  public Double getUnApprovedCount() {
    return unApprovedCount;
  }

  public void setUnApprovedCount(@javax.annotation.Nonnull Double unApprovedCount) {
    this.unApprovedCount = unApprovedCount;
  }


  public Moderator editedCount(@javax.annotation.Nonnull Double editedCount) {
    this.editedCount = editedCount;
    return this;
  }

  /**
   * Get editedCount
   * @return editedCount
   */
  @javax.annotation.Nonnull
  public Double getEditedCount() {
    return editedCount;
  }

  public void setEditedCount(@javax.annotation.Nonnull Double editedCount) {
    this.editedCount = editedCount;
  }


  public Moderator bannedCount(@javax.annotation.Nonnull Double bannedCount) {
    this.bannedCount = bannedCount;
    return this;
  }

  /**
   * Get bannedCount
   * @return bannedCount
   */
  @javax.annotation.Nonnull
  public Double getBannedCount() {
    return bannedCount;
  }

  public void setBannedCount(@javax.annotation.Nonnull Double bannedCount) {
    this.bannedCount = bannedCount;
  }


  public Moderator unFlaggedCount(@javax.annotation.Nonnull Double unFlaggedCount) {
    this.unFlaggedCount = unFlaggedCount;
    return this;
  }

  /**
   * Get unFlaggedCount
   * @return unFlaggedCount
   */
  @javax.annotation.Nonnull
  public Double getUnFlaggedCount() {
    return unFlaggedCount;
  }

  public void setUnFlaggedCount(@javax.annotation.Nonnull Double unFlaggedCount) {
    this.unFlaggedCount = unFlaggedCount;
  }


  public Moderator verificationId(@javax.annotation.Nullable String verificationId) {
    this.verificationId = verificationId;
    return this;
  }

  /**
   * Get verificationId
   * @return verificationId
   */
  @javax.annotation.Nullable
  public String getVerificationId() {
    return verificationId;
  }

  public void setVerificationId(@javax.annotation.Nullable String verificationId) {
    this.verificationId = verificationId;
  }


  public Moderator createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public Moderator moderationGroupIds(@javax.annotation.Nullable List<String> moderationGroupIds) {
    this.moderationGroupIds = moderationGroupIds;
    return this;
  }

  public Moderator addModerationGroupIdsItem(String moderationGroupIdsItem) {
    if (this.moderationGroupIds == null) {
      this.moderationGroupIds = new ArrayList<>();
    }
    this.moderationGroupIds.add(moderationGroupIdsItem);
    return this;
  }

  /**
   * Get moderationGroupIds
   * @return moderationGroupIds
   */
  @javax.annotation.Nullable
  public List<String> getModerationGroupIds() {
    return moderationGroupIds;
  }

  public void setModerationGroupIds(@javax.annotation.Nullable List<String> moderationGroupIds) {
    this.moderationGroupIds = moderationGroupIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Moderator moderator = (Moderator) o;
    return Objects.equals(this.id, moderator.id) &&
        Objects.equals(this.tenantId, moderator.tenantId) &&
        Objects.equals(this.name, moderator.name) &&
        Objects.equals(this.userId, moderator.userId) &&
        Objects.equals(this.acceptedInvite, moderator.acceptedInvite) &&
        Objects.equals(this.email, moderator.email) &&
        Objects.equals(this.markReviewedCount, moderator.markReviewedCount) &&
        Objects.equals(this.deletedCount, moderator.deletedCount) &&
        Objects.equals(this.markedSpamCount, moderator.markedSpamCount) &&
        Objects.equals(this.markedNotSpamCount, moderator.markedNotSpamCount) &&
        Objects.equals(this.approvedCount, moderator.approvedCount) &&
        Objects.equals(this.unApprovedCount, moderator.unApprovedCount) &&
        Objects.equals(this.editedCount, moderator.editedCount) &&
        Objects.equals(this.bannedCount, moderator.bannedCount) &&
        Objects.equals(this.unFlaggedCount, moderator.unFlaggedCount) &&
        Objects.equals(this.verificationId, moderator.verificationId) &&
        Objects.equals(this.createdAt, moderator.createdAt) &&
        Objects.equals(this.moderationGroupIds, moderator.moderationGroupIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantId, name, userId, acceptedInvite, email, markReviewedCount, deletedCount, markedSpamCount, markedNotSpamCount, approvedCount, unApprovedCount, editedCount, bannedCount, unFlaggedCount, verificationId, createdAt, moderationGroupIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Moderator {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    acceptedInvite: ").append(toIndentedString(acceptedInvite)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    markReviewedCount: ").append(toIndentedString(markReviewedCount)).append("\n");
    sb.append("    deletedCount: ").append(toIndentedString(deletedCount)).append("\n");
    sb.append("    markedSpamCount: ").append(toIndentedString(markedSpamCount)).append("\n");
    sb.append("    markedNotSpamCount: ").append(toIndentedString(markedNotSpamCount)).append("\n");
    sb.append("    approvedCount: ").append(toIndentedString(approvedCount)).append("\n");
    sb.append("    unApprovedCount: ").append(toIndentedString(unApprovedCount)).append("\n");
    sb.append("    editedCount: ").append(toIndentedString(editedCount)).append("\n");
    sb.append("    bannedCount: ").append(toIndentedString(bannedCount)).append("\n");
    sb.append("    unFlaggedCount: ").append(toIndentedString(unFlaggedCount)).append("\n");
    sb.append("    verificationId: ").append(toIndentedString(verificationId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    moderationGroupIds: ").append(toIndentedString(moderationGroupIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("_id");
    openapiFields.add("tenantId");
    openapiFields.add("name");
    openapiFields.add("userId");
    openapiFields.add("acceptedInvite");
    openapiFields.add("email");
    openapiFields.add("markReviewedCount");
    openapiFields.add("deletedCount");
    openapiFields.add("markedSpamCount");
    openapiFields.add("markedNotSpamCount");
    openapiFields.add("approvedCount");
    openapiFields.add("unApprovedCount");
    openapiFields.add("editedCount");
    openapiFields.add("bannedCount");
    openapiFields.add("unFlaggedCount");
    openapiFields.add("verificationId");
    openapiFields.add("createdAt");
    openapiFields.add("moderationGroupIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("_id");
    openapiRequiredFields.add("tenantId");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("userId");
    openapiRequiredFields.add("acceptedInvite");
    openapiRequiredFields.add("email");
    openapiRequiredFields.add("markReviewedCount");
    openapiRequiredFields.add("deletedCount");
    openapiRequiredFields.add("markedSpamCount");
    openapiRequiredFields.add("markedNotSpamCount");
    openapiRequiredFields.add("approvedCount");
    openapiRequiredFields.add("unApprovedCount");
    openapiRequiredFields.add("editedCount");
    openapiRequiredFields.add("bannedCount");
    openapiRequiredFields.add("unFlaggedCount");
    openapiRequiredFields.add("verificationId");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("moderationGroupIds");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Moderator
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Moderator.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Moderator is not found in the empty JSON string", Moderator.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Moderator.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Moderator` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Moderator.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("_id").toString()));
      }
      if (!jsonObj.get("tenantId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantId").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("userId") != null && !jsonObj.get("userId").isJsonNull()) && !jsonObj.get("userId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userId").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("verificationId") != null && !jsonObj.get("verificationId").isJsonNull()) && !jsonObj.get("verificationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `verificationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("verificationId").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("moderationGroupIds") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("moderationGroupIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `moderationGroupIds` to be an array in the JSON string but got `%s`", jsonObj.get("moderationGroupIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Moderator.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Moderator' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Moderator> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Moderator.class));

       return (TypeAdapter<T>) new TypeAdapter<Moderator>() {
           @Override
           public void write(JsonWriter out, Moderator value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Moderator read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Moderator given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Moderator
   * @throws IOException if the JSON string is invalid with respect to Moderator
   */
  public static Moderator fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Moderator.class);
  }

  /**
   * Convert an instance of Moderator to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

