/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.fastcomments.model.APIStatus;
import com.fastcomments.model.SearchUsersResponse;
import com.fastcomments.model.SearchUsersSectionedResponse;
import com.fastcomments.model.UserSearchResult;
import com.fastcomments.model.UserSearchSectionResult;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.fastcomments.invoker.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0-SNAPSHOT")
public class SearchUsersResult extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SearchUsersResult.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!SearchUsersResult.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'SearchUsersResult' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<SearchUsersSectionedResponse> adapterSearchUsersSectionedResponse = gson.getDelegateAdapter(this, TypeToken.get(SearchUsersSectionedResponse.class));
            final TypeAdapter<SearchUsersResponse> adapterSearchUsersResponse = gson.getDelegateAdapter(this, TypeToken.get(SearchUsersResponse.class));

            return (TypeAdapter<T>) new TypeAdapter<SearchUsersResult>() {
                @Override
                public void write(JsonWriter out, SearchUsersResult value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `SearchUsersSectionedResponse`
                    if (value.getActualInstance() instanceof SearchUsersSectionedResponse) {
                        JsonElement element = adapterSearchUsersSectionedResponse.toJsonTree((SearchUsersSectionedResponse)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `SearchUsersResponse`
                    if (value.getActualInstance() instanceof SearchUsersResponse) {
                        JsonElement element = adapterSearchUsersResponse.toJsonTree((SearchUsersResponse)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: SearchUsersResponse, SearchUsersSectionedResponse");
                }

                @Override
                public SearchUsersResult read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize SearchUsersSectionedResponse
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SearchUsersSectionedResponse.validateJsonElement(jsonElement);
                        actualAdapter = adapterSearchUsersSectionedResponse;
                        SearchUsersResult ret = new SearchUsersResult();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for SearchUsersSectionedResponse failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SearchUsersSectionedResponse'", e);
                    }
                    // deserialize SearchUsersResponse
                    try {
                        // validate the JSON object to see if any exception is thrown
                        SearchUsersResponse.validateJsonElement(jsonElement);
                        actualAdapter = adapterSearchUsersResponse;
                        SearchUsersResult ret = new SearchUsersResult();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for SearchUsersResponse failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'SearchUsersResponse'", e);
                    }

                    throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for SearchUsersResult: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public SearchUsersResult() {
        super("anyOf", Boolean.FALSE);
    }

    public SearchUsersResult(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("SearchUsersSectionedResponse", SearchUsersSectionedResponse.class);
        schemas.put("SearchUsersResponse", SearchUsersResponse.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return SearchUsersResult.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * SearchUsersResponse, SearchUsersSectionedResponse
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof SearchUsersSectionedResponse) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof SearchUsersResponse) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be SearchUsersResponse, SearchUsersSectionedResponse");
    }

    /**
     * Get the actual instance, which can be the following:
     * SearchUsersResponse, SearchUsersSectionedResponse
     *
     * @return The actual instance (SearchUsersResponse, SearchUsersSectionedResponse)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `SearchUsersSectionedResponse`. If the actual instance is not `SearchUsersSectionedResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SearchUsersSectionedResponse`
     * @throws ClassCastException if the instance is not `SearchUsersSectionedResponse`
     */
    public SearchUsersSectionedResponse getSearchUsersSectionedResponse() throws ClassCastException {
        return (SearchUsersSectionedResponse)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SearchUsersResponse`. If the actual instance is not `SearchUsersResponse`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SearchUsersResponse`
     * @throws ClassCastException if the instance is not `SearchUsersResponse`
     */
    public SearchUsersResponse getSearchUsersResponse() throws ClassCastException {
        return (SearchUsersResponse)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to SearchUsersResult
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with SearchUsersSectionedResponse
        try {
            SearchUsersSectionedResponse.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for SearchUsersSectionedResponse failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with SearchUsersResponse
        try {
            SearchUsersResponse.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for SearchUsersResponse failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format(java.util.Locale.ROOT, "The JSON string is invalid for SearchUsersResult with anyOf schemas: SearchUsersResponse, SearchUsersSectionedResponse. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of SearchUsersResult given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of SearchUsersResult
     * @throws IOException if the JSON string is invalid with respect to SearchUsersResult
     */
    public static SearchUsersResult fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, SearchUsersResult.class);
    }

    /**
     * Convert an instance of SearchUsersResult to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

