/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets SortDirections
 */
@JsonAdapter(SortDirections.Adapter.class)
public enum SortDirections {
  
  OF("OF"),
  
  NF("NF"),
  
  MR("MR");

  private String value;

  SortDirections(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SortDirections fromValue(String value) {
    for (SortDirections b : SortDirections.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<SortDirections> {
    @Override
    public void write(final JsonWriter jsonWriter, final SortDirections enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SortDirections read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SortDirections.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    SortDirections.fromValue(value);
  }
}

