/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.fastcomments.invoker.JSON;

/**
 * UpdateAPISSOUserData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class UpdateAPISSOUserData {
  public static final String SERIALIZED_NAME_GROUP_IDS = "groupIds";
  @SerializedName(SERIALIZED_NAME_GROUP_IDS)
  @javax.annotation.Nullable
  private List<String> groupIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_HAS_BLOCKED_USERS = "hasBlockedUsers";
  @SerializedName(SERIALIZED_NAME_HAS_BLOCKED_USERS)
  @javax.annotation.Nullable
  private Boolean hasBlockedUsers;

  public static final String SERIALIZED_NAME_IS_PROFILE_D_M_DISABLED = "isProfileDMDisabled";
  @SerializedName(SERIALIZED_NAME_IS_PROFILE_D_M_DISABLED)
  @javax.annotation.Nullable
  private Boolean isProfileDMDisabled;

  public static final String SERIALIZED_NAME_IS_PROFILE_COMMENTS_PRIVATE = "isProfileCommentsPrivate";
  @SerializedName(SERIALIZED_NAME_IS_PROFILE_COMMENTS_PRIVATE)
  @javax.annotation.Nullable
  private Boolean isProfileCommentsPrivate;

  public static final String SERIALIZED_NAME_IS_PROFILE_ACTIVITY_PRIVATE = "isProfileActivityPrivate";
  @SerializedName(SERIALIZED_NAME_IS_PROFILE_ACTIVITY_PRIVATE)
  @javax.annotation.Nullable
  private Boolean isProfileActivityPrivate;

  public static final String SERIALIZED_NAME_IS_COMMENT_MODERATOR_ADMIN = "isCommentModeratorAdmin";
  @SerializedName(SERIALIZED_NAME_IS_COMMENT_MODERATOR_ADMIN)
  @javax.annotation.Nullable
  private Boolean isCommentModeratorAdmin;

  public static final String SERIALIZED_NAME_IS_ADMIN_ADMIN = "isAdminAdmin";
  @SerializedName(SERIALIZED_NAME_IS_ADMIN_ADMIN)
  @javax.annotation.Nullable
  private Boolean isAdminAdmin;

  public static final String SERIALIZED_NAME_IS_ACCOUNT_OWNER = "isAccountOwner";
  @SerializedName(SERIALIZED_NAME_IS_ACCOUNT_OWNER)
  @javax.annotation.Nullable
  private Boolean isAccountOwner;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  @javax.annotation.Nullable
  private String displayName;

  public static final String SERIALIZED_NAME_DISPLAY_LABEL = "displayLabel";
  @SerializedName(SERIALIZED_NAME_DISPLAY_LABEL)
  @javax.annotation.Nullable
  private String displayLabel;

  public static final String SERIALIZED_NAME_OPTED_IN_SUBSCRIPTION_NOTIFICATIONS = "optedInSubscriptionNotifications";
  @SerializedName(SERIALIZED_NAME_OPTED_IN_SUBSCRIPTION_NOTIFICATIONS)
  @javax.annotation.Nullable
  private Boolean optedInSubscriptionNotifications;

  public static final String SERIALIZED_NAME_OPTED_IN_NOTIFICATIONS = "optedInNotifications";
  @SerializedName(SERIALIZED_NAME_OPTED_IN_NOTIFICATIONS)
  @javax.annotation.Nullable
  private Boolean optedInNotifications;

  public static final String SERIALIZED_NAME_AVATAR_SRC = "avatarSrc";
  @SerializedName(SERIALIZED_NAME_AVATAR_SRC)
  @javax.annotation.Nullable
  private String avatarSrc;

  public static final String SERIALIZED_NAME_LOGIN_COUNT = "loginCount";
  @SerializedName(SERIALIZED_NAME_LOGIN_COUNT)
  @javax.annotation.Nullable
  private Double loginCount;

  public static final String SERIALIZED_NAME_CREATED_FROM_URL_ID = "createdFromUrlId";
  @SerializedName(SERIALIZED_NAME_CREATED_FROM_URL_ID)
  @javax.annotation.Nullable
  private String createdFromUrlId;

  public static final String SERIALIZED_NAME_SIGN_UP_DATE = "signUpDate";
  @SerializedName(SERIALIZED_NAME_SIGN_UP_DATE)
  @javax.annotation.Nullable
  private Double signUpDate;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_WEBSITE_URL = "websiteUrl";
  @SerializedName(SERIALIZED_NAME_WEBSITE_URL)
  @javax.annotation.Nullable
  private String websiteUrl;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  @javax.annotation.Nullable
  private String username;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public UpdateAPISSOUserData() {
  }

  public UpdateAPISSOUserData groupIds(@javax.annotation.Nullable List<String> groupIds) {
    this.groupIds = groupIds;
    return this;
  }

  public UpdateAPISSOUserData addGroupIdsItem(String groupIdsItem) {
    if (this.groupIds == null) {
      this.groupIds = new ArrayList<>();
    }
    this.groupIds.add(groupIdsItem);
    return this;
  }

  /**
   * Get groupIds
   * @return groupIds
   */
  @javax.annotation.Nullable
  public List<String> getGroupIds() {
    return groupIds;
  }

  public void setGroupIds(@javax.annotation.Nullable List<String> groupIds) {
    this.groupIds = groupIds;
  }


  public UpdateAPISSOUserData hasBlockedUsers(@javax.annotation.Nullable Boolean hasBlockedUsers) {
    this.hasBlockedUsers = hasBlockedUsers;
    return this;
  }

  /**
   * Get hasBlockedUsers
   * @return hasBlockedUsers
   */
  @javax.annotation.Nullable
  public Boolean getHasBlockedUsers() {
    return hasBlockedUsers;
  }

  public void setHasBlockedUsers(@javax.annotation.Nullable Boolean hasBlockedUsers) {
    this.hasBlockedUsers = hasBlockedUsers;
  }


  public UpdateAPISSOUserData isProfileDMDisabled(@javax.annotation.Nullable Boolean isProfileDMDisabled) {
    this.isProfileDMDisabled = isProfileDMDisabled;
    return this;
  }

  /**
   * Get isProfileDMDisabled
   * @return isProfileDMDisabled
   */
  @javax.annotation.Nullable
  public Boolean getIsProfileDMDisabled() {
    return isProfileDMDisabled;
  }

  public void setIsProfileDMDisabled(@javax.annotation.Nullable Boolean isProfileDMDisabled) {
    this.isProfileDMDisabled = isProfileDMDisabled;
  }


  public UpdateAPISSOUserData isProfileCommentsPrivate(@javax.annotation.Nullable Boolean isProfileCommentsPrivate) {
    this.isProfileCommentsPrivate = isProfileCommentsPrivate;
    return this;
  }

  /**
   * Get isProfileCommentsPrivate
   * @return isProfileCommentsPrivate
   */
  @javax.annotation.Nullable
  public Boolean getIsProfileCommentsPrivate() {
    return isProfileCommentsPrivate;
  }

  public void setIsProfileCommentsPrivate(@javax.annotation.Nullable Boolean isProfileCommentsPrivate) {
    this.isProfileCommentsPrivate = isProfileCommentsPrivate;
  }


  public UpdateAPISSOUserData isProfileActivityPrivate(@javax.annotation.Nullable Boolean isProfileActivityPrivate) {
    this.isProfileActivityPrivate = isProfileActivityPrivate;
    return this;
  }

  /**
   * Get isProfileActivityPrivate
   * @return isProfileActivityPrivate
   */
  @javax.annotation.Nullable
  public Boolean getIsProfileActivityPrivate() {
    return isProfileActivityPrivate;
  }

  public void setIsProfileActivityPrivate(@javax.annotation.Nullable Boolean isProfileActivityPrivate) {
    this.isProfileActivityPrivate = isProfileActivityPrivate;
  }


  public UpdateAPISSOUserData isCommentModeratorAdmin(@javax.annotation.Nullable Boolean isCommentModeratorAdmin) {
    this.isCommentModeratorAdmin = isCommentModeratorAdmin;
    return this;
  }

  /**
   * Get isCommentModeratorAdmin
   * @return isCommentModeratorAdmin
   */
  @javax.annotation.Nullable
  public Boolean getIsCommentModeratorAdmin() {
    return isCommentModeratorAdmin;
  }

  public void setIsCommentModeratorAdmin(@javax.annotation.Nullable Boolean isCommentModeratorAdmin) {
    this.isCommentModeratorAdmin = isCommentModeratorAdmin;
  }


  public UpdateAPISSOUserData isAdminAdmin(@javax.annotation.Nullable Boolean isAdminAdmin) {
    this.isAdminAdmin = isAdminAdmin;
    return this;
  }

  /**
   * Get isAdminAdmin
   * @return isAdminAdmin
   */
  @javax.annotation.Nullable
  public Boolean getIsAdminAdmin() {
    return isAdminAdmin;
  }

  public void setIsAdminAdmin(@javax.annotation.Nullable Boolean isAdminAdmin) {
    this.isAdminAdmin = isAdminAdmin;
  }


  public UpdateAPISSOUserData isAccountOwner(@javax.annotation.Nullable Boolean isAccountOwner) {
    this.isAccountOwner = isAccountOwner;
    return this;
  }

  /**
   * Get isAccountOwner
   * @return isAccountOwner
   */
  @javax.annotation.Nullable
  public Boolean getIsAccountOwner() {
    return isAccountOwner;
  }

  public void setIsAccountOwner(@javax.annotation.Nullable Boolean isAccountOwner) {
    this.isAccountOwner = isAccountOwner;
  }


  public UpdateAPISSOUserData displayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @javax.annotation.Nullable
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  public UpdateAPISSOUserData displayLabel(@javax.annotation.Nullable String displayLabel) {
    this.displayLabel = displayLabel;
    return this;
  }

  /**
   * Get displayLabel
   * @return displayLabel
   */
  @javax.annotation.Nullable
  public String getDisplayLabel() {
    return displayLabel;
  }

  public void setDisplayLabel(@javax.annotation.Nullable String displayLabel) {
    this.displayLabel = displayLabel;
  }


  public UpdateAPISSOUserData optedInSubscriptionNotifications(@javax.annotation.Nullable Boolean optedInSubscriptionNotifications) {
    this.optedInSubscriptionNotifications = optedInSubscriptionNotifications;
    return this;
  }

  /**
   * Get optedInSubscriptionNotifications
   * @return optedInSubscriptionNotifications
   */
  @javax.annotation.Nullable
  public Boolean getOptedInSubscriptionNotifications() {
    return optedInSubscriptionNotifications;
  }

  public void setOptedInSubscriptionNotifications(@javax.annotation.Nullable Boolean optedInSubscriptionNotifications) {
    this.optedInSubscriptionNotifications = optedInSubscriptionNotifications;
  }


  public UpdateAPISSOUserData optedInNotifications(@javax.annotation.Nullable Boolean optedInNotifications) {
    this.optedInNotifications = optedInNotifications;
    return this;
  }

  /**
   * Get optedInNotifications
   * @return optedInNotifications
   */
  @javax.annotation.Nullable
  public Boolean getOptedInNotifications() {
    return optedInNotifications;
  }

  public void setOptedInNotifications(@javax.annotation.Nullable Boolean optedInNotifications) {
    this.optedInNotifications = optedInNotifications;
  }


  public UpdateAPISSOUserData avatarSrc(@javax.annotation.Nullable String avatarSrc) {
    this.avatarSrc = avatarSrc;
    return this;
  }

  /**
   * Get avatarSrc
   * @return avatarSrc
   */
  @javax.annotation.Nullable
  public String getAvatarSrc() {
    return avatarSrc;
  }

  public void setAvatarSrc(@javax.annotation.Nullable String avatarSrc) {
    this.avatarSrc = avatarSrc;
  }


  public UpdateAPISSOUserData loginCount(@javax.annotation.Nullable Double loginCount) {
    this.loginCount = loginCount;
    return this;
  }

  /**
   * Get loginCount
   * @return loginCount
   */
  @javax.annotation.Nullable
  public Double getLoginCount() {
    return loginCount;
  }

  public void setLoginCount(@javax.annotation.Nullable Double loginCount) {
    this.loginCount = loginCount;
  }


  public UpdateAPISSOUserData createdFromUrlId(@javax.annotation.Nullable String createdFromUrlId) {
    this.createdFromUrlId = createdFromUrlId;
    return this;
  }

  /**
   * Get createdFromUrlId
   * @return createdFromUrlId
   */
  @javax.annotation.Nullable
  public String getCreatedFromUrlId() {
    return createdFromUrlId;
  }

  public void setCreatedFromUrlId(@javax.annotation.Nullable String createdFromUrlId) {
    this.createdFromUrlId = createdFromUrlId;
  }


  public UpdateAPISSOUserData signUpDate(@javax.annotation.Nullable Double signUpDate) {
    this.signUpDate = signUpDate;
    return this;
  }

  /**
   * Get signUpDate
   * @return signUpDate
   */
  @javax.annotation.Nullable
  public Double getSignUpDate() {
    return signUpDate;
  }

  public void setSignUpDate(@javax.annotation.Nullable Double signUpDate) {
    this.signUpDate = signUpDate;
  }


  public UpdateAPISSOUserData email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public UpdateAPISSOUserData websiteUrl(@javax.annotation.Nullable String websiteUrl) {
    this.websiteUrl = websiteUrl;
    return this;
  }

  /**
   * Get websiteUrl
   * @return websiteUrl
   */
  @javax.annotation.Nullable
  public String getWebsiteUrl() {
    return websiteUrl;
  }

  public void setWebsiteUrl(@javax.annotation.Nullable String websiteUrl) {
    this.websiteUrl = websiteUrl;
  }


  public UpdateAPISSOUserData username(@javax.annotation.Nullable String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @javax.annotation.Nullable
  public String getUsername() {
    return username;
  }

  public void setUsername(@javax.annotation.Nullable String username) {
    this.username = username;
  }


  public UpdateAPISSOUserData id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UpdateAPISSOUserData instance itself
   */
  public UpdateAPISSOUserData putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateAPISSOUserData updateAPISSOUserData = (UpdateAPISSOUserData) o;
    return Objects.equals(this.groupIds, updateAPISSOUserData.groupIds) &&
        Objects.equals(this.hasBlockedUsers, updateAPISSOUserData.hasBlockedUsers) &&
        Objects.equals(this.isProfileDMDisabled, updateAPISSOUserData.isProfileDMDisabled) &&
        Objects.equals(this.isProfileCommentsPrivate, updateAPISSOUserData.isProfileCommentsPrivate) &&
        Objects.equals(this.isProfileActivityPrivate, updateAPISSOUserData.isProfileActivityPrivate) &&
        Objects.equals(this.isCommentModeratorAdmin, updateAPISSOUserData.isCommentModeratorAdmin) &&
        Objects.equals(this.isAdminAdmin, updateAPISSOUserData.isAdminAdmin) &&
        Objects.equals(this.isAccountOwner, updateAPISSOUserData.isAccountOwner) &&
        Objects.equals(this.displayName, updateAPISSOUserData.displayName) &&
        Objects.equals(this.displayLabel, updateAPISSOUserData.displayLabel) &&
        Objects.equals(this.optedInSubscriptionNotifications, updateAPISSOUserData.optedInSubscriptionNotifications) &&
        Objects.equals(this.optedInNotifications, updateAPISSOUserData.optedInNotifications) &&
        Objects.equals(this.avatarSrc, updateAPISSOUserData.avatarSrc) &&
        Objects.equals(this.loginCount, updateAPISSOUserData.loginCount) &&
        Objects.equals(this.createdFromUrlId, updateAPISSOUserData.createdFromUrlId) &&
        Objects.equals(this.signUpDate, updateAPISSOUserData.signUpDate) &&
        Objects.equals(this.email, updateAPISSOUserData.email) &&
        Objects.equals(this.websiteUrl, updateAPISSOUserData.websiteUrl) &&
        Objects.equals(this.username, updateAPISSOUserData.username) &&
        Objects.equals(this.id, updateAPISSOUserData.id)&&
        Objects.equals(this.additionalProperties, updateAPISSOUserData.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupIds, hasBlockedUsers, isProfileDMDisabled, isProfileCommentsPrivate, isProfileActivityPrivate, isCommentModeratorAdmin, isAdminAdmin, isAccountOwner, displayName, displayLabel, optedInSubscriptionNotifications, optedInNotifications, avatarSrc, loginCount, createdFromUrlId, signUpDate, email, websiteUrl, username, id, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAPISSOUserData {\n");
    sb.append("    groupIds: ").append(toIndentedString(groupIds)).append("\n");
    sb.append("    hasBlockedUsers: ").append(toIndentedString(hasBlockedUsers)).append("\n");
    sb.append("    isProfileDMDisabled: ").append(toIndentedString(isProfileDMDisabled)).append("\n");
    sb.append("    isProfileCommentsPrivate: ").append(toIndentedString(isProfileCommentsPrivate)).append("\n");
    sb.append("    isProfileActivityPrivate: ").append(toIndentedString(isProfileActivityPrivate)).append("\n");
    sb.append("    isCommentModeratorAdmin: ").append(toIndentedString(isCommentModeratorAdmin)).append("\n");
    sb.append("    isAdminAdmin: ").append(toIndentedString(isAdminAdmin)).append("\n");
    sb.append("    isAccountOwner: ").append(toIndentedString(isAccountOwner)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    displayLabel: ").append(toIndentedString(displayLabel)).append("\n");
    sb.append("    optedInSubscriptionNotifications: ").append(toIndentedString(optedInSubscriptionNotifications)).append("\n");
    sb.append("    optedInNotifications: ").append(toIndentedString(optedInNotifications)).append("\n");
    sb.append("    avatarSrc: ").append(toIndentedString(avatarSrc)).append("\n");
    sb.append("    loginCount: ").append(toIndentedString(loginCount)).append("\n");
    sb.append("    createdFromUrlId: ").append(toIndentedString(createdFromUrlId)).append("\n");
    sb.append("    signUpDate: ").append(toIndentedString(signUpDate)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    websiteUrl: ").append(toIndentedString(websiteUrl)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("groupIds");
    openapiFields.add("hasBlockedUsers");
    openapiFields.add("isProfileDMDisabled");
    openapiFields.add("isProfileCommentsPrivate");
    openapiFields.add("isProfileActivityPrivate");
    openapiFields.add("isCommentModeratorAdmin");
    openapiFields.add("isAdminAdmin");
    openapiFields.add("isAccountOwner");
    openapiFields.add("displayName");
    openapiFields.add("displayLabel");
    openapiFields.add("optedInSubscriptionNotifications");
    openapiFields.add("optedInNotifications");
    openapiFields.add("avatarSrc");
    openapiFields.add("loginCount");
    openapiFields.add("createdFromUrlId");
    openapiFields.add("signUpDate");
    openapiFields.add("email");
    openapiFields.add("websiteUrl");
    openapiFields.add("username");
    openapiFields.add("id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateAPISSOUserData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateAPISSOUserData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateAPISSOUserData is not found in the empty JSON string", UpdateAPISSOUserData.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("groupIds") != null && !jsonObj.get("groupIds").isJsonNull() && !jsonObj.get("groupIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `groupIds` to be an array in the JSON string but got `%s`", jsonObj.get("groupIds").toString()));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      if ((jsonObj.get("displayLabel") != null && !jsonObj.get("displayLabel").isJsonNull()) && !jsonObj.get("displayLabel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayLabel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayLabel").toString()));
      }
      if ((jsonObj.get("avatarSrc") != null && !jsonObj.get("avatarSrc").isJsonNull()) && !jsonObj.get("avatarSrc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `avatarSrc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("avatarSrc").toString()));
      }
      if ((jsonObj.get("createdFromUrlId") != null && !jsonObj.get("createdFromUrlId").isJsonNull()) && !jsonObj.get("createdFromUrlId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdFromUrlId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdFromUrlId").toString()));
      }
      if ((jsonObj.get("email") != null && !jsonObj.get("email").isJsonNull()) && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
      if ((jsonObj.get("websiteUrl") != null && !jsonObj.get("websiteUrl").isJsonNull()) && !jsonObj.get("websiteUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `websiteUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("websiteUrl").toString()));
      }
      if ((jsonObj.get("username") != null && !jsonObj.get("username").isJsonNull()) && !jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateAPISSOUserData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateAPISSOUserData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateAPISSOUserData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateAPISSOUserData.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateAPISSOUserData>() {
           @Override
           public void write(JsonWriter out, UpdateAPISSOUserData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateAPISSOUserData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             UpdateAPISSOUserData instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateAPISSOUserData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateAPISSOUserData
   * @throws IOException if the JSON string is invalid with respect to UpdateAPISSOUserData
   */
  public static UpdateAPISSOUserData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateAPISSOUserData.class);
  }

  /**
   * Convert an instance of UpdateAPISSOUserData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

