/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmailTemplateDefinition
 */
public class EmailTemplateDefinitionTest {
    private final EmailTemplateDefinition model = new EmailTemplateDefinition();

    /**
     * Model tests for EmailTemplateDefinition
     */
    @Test
    public void testEmailTemplateDefinition() {
        // TODO: test EmailTemplateDefinition
    }

    /**
     * Test the property 'emailTemplateId'
     */
    @Test
    public void emailTemplateIdTest() {
        // TODO: test emailTemplateId
    }

    /**
     * Test the property 'defaultTestData'
     */
    @Test
    public void defaultTestDataTest() {
        // TODO: test defaultTestData
    }

    /**
     * Test the property 'defaultTranslationsByLocale'
     */
    @Test
    public void defaultTranslationsByLocaleTest() {
        // TODO: test defaultTranslationsByLocale
    }

    /**
     * Test the property 'defaultEJS'
     */
    @Test
    public void defaultEJSTest() {
        // TODO: test defaultEJS
    }

}
