/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import com.fastcomments.model.APIStatus;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetV2PageReactUsersResponse
 */
public class GetV2PageReactUsersResponseTest {
    private final GetV2PageReactUsersResponse model = new GetV2PageReactUsersResponse();

    /**
     * Model tests for GetV2PageReactUsersResponse
     */
    @Test
    public void testGetV2PageReactUsersResponse() {
        // TODO: test GetV2PageReactUsersResponse
    }

    /**
     * Test the property 'userNames'
     */
    @Test
    public void userNamesTest() {
        // TODO: test userNames
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
