/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import com.fastcomments.model.APIStatus;
import com.fastcomments.model.CommentUserBadgeInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RemoveUserBadgeResponse
 */
public class RemoveUserBadgeResponseTest {
    private final RemoveUserBadgeResponse model = new RemoveUserBadgeResponse();

    /**
     * Model tests for RemoveUserBadgeResponse
     */
    @Test
    public void testRemoveUserBadgeResponse() {
        // TODO: test RemoveUserBadgeResponse
    }

    /**
     * Test the property 'badges'
     */
    @Test
    public void badgesTest() {
        // TODO: test badges
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
