/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import com.fastcomments.model.APIStatusFAILED;
import com.fastcomments.model.CustomConfigParameters;
import com.fastcomments.model.FComment;
import com.fastcomments.model.PickAPIErrorInternalExcludeKeyofAPIErrorInternalStatusCode;
import com.fastcomments.model.SaveCommentResponse;
import com.fastcomments.model.UserSessionInfo;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SaveComment200Response
 */
public class SaveComment200ResponseTest {
    private final SaveComment200Response model = new SaveComment200Response();

    /**
     * Model tests for SaveComment200Response
     */
    @Test
    public void testSaveComment200Response() {
        // TODO: test SaveComment200Response
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'moduleData'
     */
    @Test
    public void moduleDataTest() {
        // TODO: test moduleData
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'secondaryCode'
     */
    @Test
    public void secondaryCodeTest() {
        // TODO: test secondaryCode
    }

    /**
     * Test the property 'bannedUntil'
     */
    @Test
    public void bannedUntilTest() {
        // TODO: test bannedUntil
    }

    /**
     * Test the property 'maxCharacterLength'
     */
    @Test
    public void maxCharacterLengthTest() {
        // TODO: test maxCharacterLength
    }

    /**
     * Test the property 'translatedError'
     */
    @Test
    public void translatedErrorTest() {
        // TODO: test translatedError
    }

    /**
     * Test the property 'customConfig'
     */
    @Test
    public void customConfigTest() {
        // TODO: test customConfig
    }

}
