/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateDomainConfigParams
 */
public class UpdateDomainConfigParamsTest {
    private final UpdateDomainConfigParams model = new UpdateDomainConfigParams();

    /**
     * Model tests for UpdateDomainConfigParams
     */
    @Test
    public void testUpdateDomainConfigParams() {
        // TODO: test UpdateDomainConfigParams
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'emailFromName'
     */
    @Test
    public void emailFromNameTest() {
        // TODO: test emailFromName
    }

    /**
     * Test the property 'emailFromEmail'
     */
    @Test
    public void emailFromEmailTest() {
        // TODO: test emailFromEmail
    }

    /**
     * Test the property 'logoSrc'
     */
    @Test
    public void logoSrcTest() {
        // TODO: test logoSrc
    }

    /**
     * Test the property 'logoSrc100px'
     */
    @Test
    public void logoSrc100pxTest() {
        // TODO: test logoSrc100px
    }

    /**
     * Test the property 'footerUnsubscribeURL'
     */
    @Test
    public void footerUnsubscribeURLTest() {
        // TODO: test footerUnsubscribeURL
    }

    /**
     * Test the property 'emailHeaders'
     */
    @Test
    public void emailHeadersTest() {
        // TODO: test emailHeaders
    }

}
