/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import com.fastcomments.model.NotificationType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserNotification
 */
public class UserNotificationTest {
    private final UserNotification model = new UserNotification();

    /**
     * Model tests for UserNotification
     */
    @Test
    public void testUserNotification() {
        // TODO: test UserNotification
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'anonUserId'
     */
    @Test
    public void anonUserIdTest() {
        // TODO: test anonUserId
    }

    /**
     * Test the property 'urlId'
     */
    @Test
    public void urlIdTest() {
        // TODO: test urlId
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'pageTitle'
     */
    @Test
    public void pageTitleTest() {
        // TODO: test pageTitle
    }

    /**
     * Test the property 'relatedObjectType'
     */
    @Test
    public void relatedObjectTypeTest() {
        // TODO: test relatedObjectType
    }

    /**
     * Test the property 'relatedObjectId'
     */
    @Test
    public void relatedObjectIdTest() {
        // TODO: test relatedObjectId
    }

    /**
     * Test the property 'viewed'
     */
    @Test
    public void viewedTest() {
        // TODO: test viewed
    }

    /**
     * Test the property 'isUnreadMessage'
     */
    @Test
    public void isUnreadMessageTest() {
        // TODO: test isUnreadMessage
    }

    /**
     * Test the property 'sent'
     */
    @Test
    public void sentTest() {
        // TODO: test sent
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'fromCommentId'
     */
    @Test
    public void fromCommentIdTest() {
        // TODO: test fromCommentId
    }

    /**
     * Test the property 'fromVoteId'
     */
    @Test
    public void fromVoteIdTest() {
        // TODO: test fromVoteId
    }

    /**
     * Test the property 'fromUserName'
     */
    @Test
    public void fromUserNameTest() {
        // TODO: test fromUserName
    }

    /**
     * Test the property 'fromUserId'
     */
    @Test
    public void fromUserIdTest() {
        // TODO: test fromUserId
    }

    /**
     * Test the property 'fromUserAvatarSrc'
     */
    @Test
    public void fromUserAvatarSrcTest() {
        // TODO: test fromUserAvatarSrc
    }

    /**
     * Test the property 'optedOut'
     */
    @Test
    public void optedOutTest() {
        // TODO: test optedOut
    }

}
