/*
 * fastcomments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: support@fastcomments.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fastcomments.model;

import com.fastcomments.model.ImportedAPIStatusFAILED;
import com.fastcomments.model.ImportedAPIStatusSUCCESS;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VoteResponseStatus
 */
public class VoteResponseStatusTest {
    private final VoteResponseStatus model = new VoteResponseStatus();

    /**
     * Model tests for VoteResponseStatus
     */
    @Test
    public void testVoteResponseStatus() {
        // TODO: test VoteResponseStatus
    }

}
